### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Yunkong690** [xyh19981224/Hackintosh-OC-Hasee-Z7M-SL7#1]
哈喽，请问一下你的EFI可以安装上MacOS12吗 我的不管咋配置都不行

**Comment by XiaOldMan** [comment]
现在这台电脑正常使用系统是macOS 11.7.1，12没有进行安装测试。之前进行U盘安装macOS 12时报错，暂时没有进行处理，因为我又组装了一台新的黑苹果。 现在这个笔记本性能不满足我开发需求了。
